var datas=[{musique: "The Other Side of Paradise", description_text:"J’ai découvert cette musique il y a six ans grâce à une animation sur YouTube. Ce titre et le titre <i>Youth</i> m’ont introduit à ce groupe. Je les ai redécouverts deux ans plus tard. Glass Animals est aujourd’hui l’artiste musical que j’écoute le plus.<br><br> Les voir en concert en octobre 2024 a renforcé mon amour pour ce groupe. Leur capacité à jouer en live et de créer un échange avec le public est impressionnante. Cette expérience restera gravée à jamais dans ma mémoire.", nom_audio:"audio/TheOtherSideOfParadise.mp3", id_audio:"audio1", lien_spotify:"https://open.spotify.com/intl-fr/track/0rRjGruFonCGOt0S5zAJNQ", button:"button1", img:"img/GlassAnimals.jpg", lien_deezer:"https://deezer.page.link/omkremoN893HJAVE9", lien_youtube:"https://youtu.be/RMPX_vgqQnM?si=n-tGHlynZBjvkHkd", artiste:"Glass Animals"},

{musique: "In Between", description_text:"C’est au cours d’un long trajet en voiture aux côtés de mon père que mon père m'a fait découvrir cette musique. Je ne m’attendais pas à l'aimer autant dès la première écoute.<br><br> Lui non plus ne devait pas s’attendre à aimer autant ce groupe, car par la suite je fus la seule à écouter plus de leur discographie. Cela n’a pas pris longtemps avant qu’il découvre qu’il aime leur musique tout autant que moi. Cette appréciation commune pour Beartooth nous a permis d’aller les voir en concert ensemble.<br><br>Ce titre reste encore aujourd’hui ma musique favorite de Beartooth, qui est mon premier artiste métal sur Spotify.", nom_audio:"audio/InBetween.mp3",id_audio:"audio2", button:"button2", lien_spotify:"https://open.spotify.com/intl-fr/track/03jdl5GTBhKsgB1Yw8mVPh", lien_deezer:"https://deezer.page.link/1nsgCSPyBRXf8PW47", lien_youtube:"https://youtu.be/j2p_w409y-o?si=yGEAC-iX5Jrq59yd", img:"img/Beartooth.jpg", artiste:"Beartooth"},

{musique: "Brother", description_text:"Découvert grâce à une fan-animation sur YouTube, <i>Brother</i> est immédiatement devenue ma chanson préférée. Au début par son association avec cette animation, aujourd’hui par son association avec une partie importante de ma vie.<br><br>Elle m’évoque des souvenirs heureux et mélancoliques, et me provoque des émotions fortes et un puissant sentiment de nostalgie. Pour la plupart, je ne saurais les expliquer. Je peux seulement dire que c’est une des seules musiques, voir la seule, qui crée un tel mélange de sentiments.<br><br>J’espère ne jamais me lasser de cette musique.", nom_audio:"audio/Brother.mp3",id_audio:"audio3", button:"button3", lien_spotify:"https://open.spotify.com/intl-fr/track/65gLJGey4u4KFFqoC5fzFJ", lien_deezer:"https://deezer.page.link/M2iAQ5FQTyyuD26UA", lien_youtube:"https://youtu.be/FSKZxOmmw0Y?si=FzYmv0ccRNmR6aai", img:"img/Kodaline.jpg", artiste:"Kodaline"},

{musique: "The Horror and the Wild", description_text:"Malgré que <i>The Horror and the Wild</i> soit la musique la plus populaire du groupe The Amazing Devil, ce n’est pas la première chanson que j’ai entendue d’eux. Groupe que j’ai découvert en 2021 avec <i>Elsa’s Song</i> grâce au même artiste qui m’a fait découvrir <i>Brother</i> de Kodaline, je n’ai pas écouté d’autres de leurs musiques avant 2023. <br><br>Ce groupe a été un gros coup de cœur. Une fois que j’ai entendu une des musiques de leur album de 2020, je me suis lancé dans l’écoute de leur discographie complète.<br><br>Le lyrisme dont ils font preuve et le récit qu’ils arrivent à créer est une grande inspiration pour moi.", nom_audio:"audio/TheHorrorandtheWild.mp3", id_audio:"audio4", button:"button4", lien_spotify:"https://open.spotify.com/intl-fr/track/2JV3zPHRCzw7w8NA4wT7r3", lien_deezer:"https://deezer.page.link/ks3XC6DCBo9JgkQV7", lien_youtube:"https://youtu.be/NAskjmeIvg0?si=E5O2G4MF4itnr6Dn", img:"img/TheAmazingDevil.jpg", artiste:"The Amazing Devil"},

{musique:"Midnight City", description_text:"Je me rappelle avec tendresse les premières fois où j’ai écouté <i>Midnight City</i> dans la voiture de mon père. J’étais encore enfant, cette chanson étant sortie en 2011, mais pourtant, je me rappelle avec certitude que ce morceau était déjà dans mes favoris. Je ne m’en étais pas encore rendue compte, n’ayant pas spécialement de réflections sur mes musiques préférées. Mais plus de dix ans plus tard, je reviens toujours vers elle.<br><br>C’est seulement très récemment que j’ai commencé à écouter plus de musiques de M83, et j’espère pouvoir un jour les voir en concert. Je pense que cela doit être une expérience éthérée.", nom_audio:"audio/MidnightCity.mp3", id_audio:"audio5", button:"button5", lien_spotify:"https://open.spotify.com/intl-fr/track/6GyFP1nfCDB8lbD2bG0Hq9", lien_deezer:"https://deezer.page.link/JGYX6ZRu8wHYhZEH7", lien_youtube:"https://youtu.be/dX3k_QDnzHE?si=fIb_IULHFt338Ylh", img:"img/M83.jpg", artiste:"M83"}]

var button="⏵"